openapi: 3.0.2
info:
  title: Filecoin JSON REST Actor API 
  description: Filecoin JSON REST Actor API Description
  version: 0.1.0
servers:
- url: http://127.0.0.1:3453/api/actor/v0
paths:
  /actors:
    get:
      summary: List actirs
      description: List actors currently known to this node in ID order
      parameters:
      - name: nextPageToken
        in: query
        description: Next page token
        required: false
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Actor'
  /actors/{actorId}:
    get:
      summary: Find actor by ID
      description: Find a single actor record by ID
      parameters: 
      - name: actorId
        in: path
        description: ID of the Actor to fetch
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Actor'
components:
  schemas:
    Actor:
      type: object
      properties:
        kind:
          type: string
          enum: [actor]
        id: 
          type: string
        role:
          type: string
          enum: [miner,user,storageMarket,paymentBroker]
        nonce:
          type: number
        balance:
          type: number
        stateRoot:
          type: string
        state: 
          type: object
          description: Role specific properties    